### ISSUE TITLE
[BUG] Cannot add color and displayName toogether to arc__* fields

### ISSUE THREAD

**Issue by k8spacket** [hoptical/nodegraph-api-plugin#18] opened 2022-07-01 18:19 UTC
**Describe the bug**
Cannot add `color` and `displayName` to `arc__*` fields toogether

**To Reproduce**

field json example
```
{
  color: "green",
  field_name: "arc__1",
  type: "number",
  displayName: "Display name of arc1 field"
}
```

**Expected behavior**
The border of the node should be colored green.
Display name should be visible in the legend on the bottom left.

**Current behavior**
I suppose to the field is added `displayName` only, because of this part of the code:
```
if ('color' in field) {
  outputField.config = { color: { fixedColor: field['color'], mode: FieldColorModeId.Fixed } };
}
if ('displayName' in field) {
  outputField.config = { displayName: field['displayName'] };
}
```
The `outputField.config` is overridden, and information about color is lost.

**Comment by hoptical** [comment] 2022-07-03 20:03
@k8spacket Thanks for reaching out. 
This issue has been fixed in [v1.0.1](https://github.com/hoptical/nodegraph-api-plugin/releases/tag/v1.0.1). Please check it out. Looking forward to your feedback.

**Comment by k8spacket** [comment] 2022-07-03 20:47
@hoptical Glad to hear it. Thanks for that PR. Do you know how long takes the process of updating the plugin in the Grafana Plugins repo? Can you estimate when it will be available there?

**Comment by k8spacket** [comment] 2022-07-10 14:38
@hoptical Version 1.0.1 is published. I've checked and the display name for the arc__* field is visible in the legend 👏 .
Unfortunately, there is another bug (I didn't find why yet). See attached gif.

![issue](https://user-images.githubusercontent.com/95187481/178149339-8815b511-5531-46d6-a0a8-250151978349.gif)

The problem is connected with the previous `display name`/`display names` when I switch the grafana filter.
I've checked, and my endpoint on `/api/graph/fields` doesn't return additional fields. Only according to the currently selected graph mode.

Do you have any idea?

**Comment by hoptical** [comment] 2022-07-10 15:35
@k8spacket Thanks again for the feedback. I'll try reproducing the bug and get back to you. It may take a week because of being busy these days.
I'll do my best to make it quick.

**Comment by hoptical** [comment] 2022-07-19 07:23
@k8spacket Please send the variables you have defined in your dashboard setting. Are they altering the query string?

**Comment by k8spacket** [comment] 2022-07-19 12:48
@hoptical Configuration of the plugin you can find here: https://github.com/k8spacket#installation

Dashboard configuration based on your plugin is here: https://github.com/k8spacket/k8spacket/blob/master/dashboards/k8s-packet-node-graph.yaml

I hope it is enough for that moment. If not, I will be able send more at the beginning of August.

**Comment by hoptical** [comment] 2022-07-19 15:43
@k8spacket I checked out your dashboard, and you have used the variables in [query string](https://github.com/k8spacket/k8spacket/blob/a86c9e0bb598dcd23f2cbea1c532b70b20f4cef3/dashboards/k8s-packet-node-graph.yaml#L57).
So I tried reproducing the bug. I defined a custom variable and used it in the query string, same as you. As you can see in the attached gif, by altering the variable in the dropdown, the route of the field is called again, and it successfully returns the new fields, including the legends. (_mainStat_ and _secondaryStat_). I've attached the flask code too.

What is your Grafana version? Mine is v9.0.1. Please check your API server again. Maybe it doesn't return the correct fields. If not, help me with more detail to reproduce the bug. 

![screen-capture (3)](https://user-images.githubusercontent.com/30399989/179791662-f054a882-b9b3-4cd7-9116-e6260e23e251.gif)
[run.zip](https://github.com/hoptical/nodegraph-api-plugin/files/9142644/run.zip)

**Comment by k8spacket** [comment] 2022-07-19 17:57
@hoptical Thanks for your effort. At the beginning of August I will check again. For now I can say that my version of Grafana is less than 9.0 (I don't remember exactly). I will install the newest version of Grafana, make this check again and back with results.

**Comment by hoptical** [comment] 2022-07-26 12:53
I'm going to close the issue for now but looking forward to your feedback.

**Comment by k8spacket** [comment] 2022-08-06 12:40
Haha, @hoptical 
I'm wondering what your face will look like after reading this message 😄 

The problem appears when `displayName` for `mainStat` or `secondaryStat` is the same as for `arc__*` fields

I'm pretty sure this problem will appear when you add these changes:
```
    if var == "connection":

        nodes_fields = [{"field_name": "id", "type": "string"},
                        {"field_name": "title", "type": "string",
                         },
                        {"field_name": "subTitle", "type": "string"},
                        {"field_name": "mainStat", "type": "string",
                            "displayName": "Connected"},
                        {"field_name": "secondaryStat",
                            "type": "number",  "displayName": "Closed"},
                        {"field_name": "arc__failed",
                        "type": "number", "color": "red", "displayName": "Connected"},
                        {"field_name": "arc__passed",
                        "type": "number", "color": "green", "displayName": "Closed"},
                        {"field_name": "detail__role",
                        "type": "string", "displayName": "Role"}]
```
Maybe for `var!=connection`, the same changes must be done. 

I didn't test it with your app. Are you able to do it?

**Comment by hoptical** [comment] 2022-08-06 21:06
@k8spacket Thanks for the update and your detailed feedback.
The bug is reproducible by changing the variable or returning data containing different fields (like the attached file). And as you said:
> it appears when `displayName` for `mainStat` or `secondaryStat` is the same as for `arc__*` fields

I checked the source code again and couldn't find any clue for the bug. That's why I'd make a guess that it is due to the [nodeGraph panel code](https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/nodeGraph), not this data source.
BTW, I will make sure and get back to you.

[run.zip](https://github.com/hoptical/nodegraph-api-plugin/files/9275763/run.zip)

**Comment by k8spacket** [comment] 2022-08-07 05:06
@hoptical I analyzed your code and have the same feelings: this funny, weird corner case is connected to Grafana Node Graph implementation.

An easy workaround, for now, is adding space in `displayName` for `mainStat` and `secondaryStat`:

```
        nodes_fields = [{"field_name": "id", "type": "string"},
                        {"field_name": "title", "type": "string",
                         },
                        {"field_name": "subTitle", "type": "string"},
                        {"field_name": "mainStat", "type": "string",
                            "displayName": "Connected "},
                        {"field_name": "secondaryStat",
                            "type": "number",  "displayName": "Closed "},
                        {"field_name": "arc__failed",
                        "type": "number", "color": "red", "displayName": "Connected"},
                        {"field_name": "arc__passed",
                        "type": "number", "color": "green", "displayName": "Closed"},
                        {"field_name": "detail__role",
                        "type": "string", "displayName": "Role"}]
```

**Comment by hoptical** [comment] 2022-08-07 10:51
Yes. Would you report the bug in the [Grafana issues](https://github.com/grafana/grafana/issues)?

**Comment by k8spacket** [comment] 2022-08-08 08:33
Reported: https://github.com/grafana/grafana/issues/53373

**Closed** 2022-08-30 15:47 UTC
Labels: bug
